# netlify.toml

# Build Settings
[build]
  # The command to build your project. Replace with your build command.
  command = "npm run build"
  
  # The directory where the built files are located after the build process.
  publish = "build"

# Environment Variables
[build.environment]
  # Define environment variables for your build process.
  # For example, setting a Node.js version:
  NODE_VERSION = "14"
  
  # You can also define secrets and access them in your build.
  # SECRET_API_KEY = "your-secret-api-key"

# Build Hooks
[build]
  # Specify build hooks to run before and after the build.
  # These can be used for various purposes like caching dependencies.
  prebuild = "npm install"
  postbuild = "npm run postbuild"

# Redirects and Rewrites
[[redirects]]
  # Redirects URLs to other paths or external URLs.
  from = "/old-page"
  to = "/new-page"
  status = 301 # Optional: Set the HTTP status code (default is 301).

[[redirects]]
  # You can define multiple redirects.

[[headers]]
  # Custom HTTP headers for your site.
  # Useful for setting security headers, caching, etc.
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Asset Optimization (Optional)
[build.processing]
  # Enable asset optimization to automatically optimize images and other assets.
  # More options are available in the documentation.
  "images/**/*.jpg" = { action = "optimize", use = "webp" }
  "images/**/*.png" = { action = "optimize" }
  
# Plugins (Optional)
[[plugins]]
  package = "@netlify/plugin-name"
  # Configuration options for the plugin can be specified here.

# Redirects (Optional)
[[redirects]]
  # Define redirects for specific paths.
  from = "/old-path"
  to = "/new-path"
  status = 301 # Optional: Set the HTTP status code (default is 301).

[[redirects]]
  # You can define multiple redirects.

# Headers (Optional)
[[headers]]
  # Define custom HTTP headers for specific paths.
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Contexts (Optional)
[context.production]
  # Context-specific settings for production.
  command = "npm run build:production"
  publish = "build/production"

[context.deploy-preview]
  # Context-specific settings for deploy previews.
  command = "npm run build:preview"
  publish = "build/preview"

[context.branch-deploy]
  # Context-specific settings for branch deploys.
  command = "npm run build:branch"
  publish = "build/branch"
